### ISSUE TITLE
Error with List Instances: Need to delete existing content types before adding new ones

### ISSUE THREAD

**Issue by olemp** [olemp/js-sites-core#14]

**Comment by olemp** [comment]
Solved in https://github.com/Puzzlepart/js-sites-core/commit/b000cd5450e23b32498311ad66c4eaadc19cee33, @tarjeieo?

**Comment by tarjeieo** [comment]
Nope, still some snags

**Comment by olemp** [comment]
It's included in v1.8.4. At least it's better then it was.

**Comment by tarjeieo** [comment]
Pushed a new fix now that I believe should work

**Comment by olemp** [comment]
Merged.
